package:
  name: revbayes-kernel
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }} 

source:
  git: https://github.com/eaton-lab/revbayes_kernel.git

build:
  script: build.sh
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - rb-jupyter
  run:
    - jupyter
    - rb-jupyter

about:
  home: https://github.com/revbayes/revbayes_kernel
  license: MIT
  summary: A Jupyter kernel for RevBayes
